// Single schema entry point for drizzle-kit and the Better Auth adapter.
// auth-schema.ts is generated by `npm run auth:generate`; rerun it after
// changing the Better Auth config or plugins.
export * from "./auth-schema";
export * from "./cart-schema";
export * from "./catalog-schema";
export * from "./order-schema";
export * from "./wishlist-schema";
